### ISSUE TITLE
Implementation of `Rules`

### ISSUE THREAD

**Issue by floriansalihovic** [floriansalihovic/udacity_rsp#1]
A rule determines wether a player beat another or if the outcome of two players making their moves ended in a draw.

## Tech notes:
- Player class needs to define a method to make a move, which is evaluated by the rules
- Rules are well defined: Rock beats Scissor, Scissor beat Paper, Paper beats Rock
- The outcome must be stored for game statistics

**Comment by 40young** [comment]
so with the notes above are you saying I need to 'def beats' in each player class?

**Comment by floriansalihovic** [comment]
Nope, it is required to have rules, which can evaluate the result of two players making a move.

**Comment by floriansalihovic** [comment]
Putting it differently: we won’t implement the one final solution right away. We‘ll nee to change the code according to new requirements. The better the abstraction, the less refactoring we have to change on the long run.
